PRINT "= Launch".

LOCK STEERING TO UP.
LOCK THROTTLE TO 1.
STAGE.

WAIT UNTIL MAXTHRUST = 0.
PRINT "Releasing solid booster".
WAIT 0.5.
STAGE.
LOCK THROTTLE TO 0.
WAIT UNTIL VERTICALSPEED <= 0.
PRINT "= Launch complete".
